### PR TITLE
bump product to 2020.1

### PR DESCRIPTION
**Pull request by slestak**
builds and runs on my workstation.

Ref #15

### CODE REVIEW

**Review by ronhks — APPROVED** [review]
nice job, thanks! :)

**Comment by slestak** [comment]
Will still need chathurabuddi blessing to get it published.

**Comment by slestak** [comment]
Good day Chathura.  Can this be merged?

**Comment by chathurabuddi** [comment]
Hi @slestak ,
Thanks for your contribution. Please accept my apologies for the little delay.

**Pull request merged**
